mysql:
  path:
  port: 6033
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: airgo
  username: airgo
  password:
  max-idle-conns: 10
  max-open-conns: 100
system:
  admin-email: admin@oicq.com
  admin-password: admin
  port: 8899
  db-type: sqlite
sqlite:
  path: ./test.db