name: Build and Release
on:
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  build:
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64 ]
      fail-fast: false
    runs-on: ubuntu-latest
#    env:
#      GOOS: ${{ matrix.goos }}
#      GOARCH: ${{ matrix.goarch }}
#      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Build
        run: |
          cd server
          go build -o AirGo-${{matrix.goos}}-${{matrix.goarch}} main.go

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./AirGo-${{matrix.goos}}-${{matrix.goarch}}
          tag: ${{ github.ref }}
          file_glob: true
