name: Publish Go Binary
on:
  release:
    types:
      - created
jobs:
  buildAndDeploy:
    runs-on:  ubuntu-latest
    # 交叉构建,多平台交叉编译
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
    # 使用checkout
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
#          go-version: '>=1.16.0'
          go-version: 1.19
      - run: go version

      - name: build
        run: |
          cd server
          go build -o AirGo-${{matrix.goos}}-${{matrix.goarch}} main.go

#      - name: Packaging...
#        run: tar czf AirGo-${{matrix.goos}}-${{matrix.goarch}}.tgz AirGo-${{matrix.goos}}-${{matrix.goarch}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Uploading assets...
        # if: ${{ !env.ACT }}
        # id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./AirGo-${{matrix.goos}}-${{matrix.goarch}}.tgz
          asset_name: AirGo-${{matrix.goos}}-${{matrix.goarch}}.tgz
          asset_content_type: application/gzip
