name: build-go-binary
on:
  release:
    types: [created,published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ] # 需要打包的系统
        goarch: [ amd64 ] # 需要打包的架构
#        goos: [linux, darwin] # 需要打包的系统
#        goarch: [amd64, arm64, arm32] # 需要打包的架构
#        exclude: # 排除某些平台和架构
#          - goarch: arm64
#            goos: darwin
#          - goarch: arm32
#            goos: darwin
    steps:
      - name: dependence
        run: |
          sudo apt update -y
          sudo apt install gcc-aarch64-linux-gnu -y 
          sudo apt-get install gcc-arm-linux-gnueabihf -y
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19 # 指定编译使用的 Golang 版本
          binary_name: "AirGo" # 可以指定二进制文件的名称
          extra_files: ./server/config.yaml # 需要包含的额外文件
          project_path: "./server"
          pre_command: "CGO_ENABLED=1 GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} "
#  build-windows
#     runs-on: ubuntu-latest
